"""Build ArtworkStudio — the single-process desktop app — as a fully-frozen
one-dir Windows package with EVERYTHING bundled (Python, all dependencies,
Chromium). Nothing installs at runtime.

Difference from build_agent.py:
  * Entry point is studio_gui.py (the tray/window app), imported STATICALLY, so
    PyInstaller's dependency scan discovers app.py, agent.py, local_worker.py,
    src/, config/ and their third-party deps directly — there is no dynamic
    code/ bootstrap and no self-update baseline.
  * cv2 (OpenCV) IS bundled: everything runs in one process now, so the
    aspect-ratio / replace-text similarity in src/compare.py runs locally.
  * fastapi / uvicorn / starlette ARE bundled: the web server runs locally now.
  * static/ (the web UI) is shipped as data and resolved via sys._MEIPASS by
    app.STATIC_DIR.

Run inside the activated venv:  python build_studio.py
Produces:  dist/ArtworkStudio/ArtworkStudio.exe  and  dist/ArtworkStudio.zip
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path


def chromium_folder() -> Path:
    """Resolve the exact chromium-<ver> folder the installed Playwright uses."""
    from playwright.sync_api import sync_playwright
    pw = sync_playwright().start()
    try:
        exe = pw.chromium.executable_path
    finally:
        pw.stop()
    p = Path(exe)
    for parent in p.parents:
        if re.match(r"chromium-\d+$", parent.name):
            return parent
    raise RuntimeError(f"Could not locate chromium-<ver> folder from {exe}")


# Only exclude genuinely unused heavy sweeps. Unlike the agent build we KEEP
# cv2, fastapi, uvicorn, starlette — they all run in this one process now.
EXCLUDES = [
    "scipy", "imagehash",   # pHash is numpy-only; these are large and unused.
    "matplotlib", "PyQt5", "PyQt6", "PySide2", "PySide6",
    "pandas", "notebook", "IPython", "tkinter.test", "test",
]

_SPEC_TEMPLATE = '''# Auto-generated by build_studio.py — do not edit by hand.
# One-dir, fully-frozen ArtworkStudio: Python + all deps + Chromium bundled.
import os
from PyInstaller.utils.hooks import collect_all, collect_submodules

CHROME_DIR = r"{chrome_dir}"
CHROME_PREFIX = "ms-playwright/{chrome_name}"

# Collect data files, binaries and submodules for every runtime dependency.
# Even though studio_gui.py imports these statically, collect_all guarantees the
# non-Python assets come along: tkinter's Tcl/Tk, PIL codecs, numpy/cv2 DLLs,
# and uvicorn/fastapi/starlette/pydantic data.
_datas, _binaries, _hidden = [], [], []
for _pkg in ("playwright", "tkinter", "PIL", "pystray", "numpy", "cv2",
             "requests", "dotenv", "certifi", "charset_normalizer",
             "fastapi", "starlette", "uvicorn", "pydantic", "pydantic_core",
             "anyio", "sniffio", "click", "h11", "multipart"):
    try:
        _d, _b, _h = collect_all(_pkg)
        _datas += _d
        _binaries += _b
        _hidden += _h
    except Exception as _exc:
        print(f"[spec] collect_all({{_pkg!r}}) skipped: {{_exc}}")

# uvicorn loads its protocol/lifespan implementations lazily by string name;
# name them so the frozen build can find them.
try:
    _hidden += collect_submodules("uvicorn")
except Exception:
    pass
_hidden += ["_tkinter", "tkinter"]

# Recursively enumerate the Chromium folder into (source, dest_dir) 2-tuples.
chrome_datas = []
for _r, _d, _files in os.walk(CHROME_DIR):
    for _f in _files:
        _src = os.path.join(_r, _f)
        _reldir = os.path.relpath(_r, CHROME_DIR)
        _dest = CHROME_PREFIX if _reldir == "." else os.path.join(CHROME_PREFIX, _reldir)
        chrome_datas.append((_src, _dest))

# Ship the web UI (static/) as read-only data. app.STATIC_DIR resolves it from
# sys._MEIPASS at runtime. config/ and src/ are Python packages discovered by
# the import scan, but we also ship any non-.py data they contain.
asset_datas = []
for _r, _d, _files in os.walk("static"):
    for _f in _files:
        _src = os.path.join(_r, _f)
        asset_datas.append((_src, _r))

a = Analysis(
    ["studio_gui.py"],
    pathex=[r"{root}"],
    binaries=_binaries,
    datas=asset_datas + chrome_datas + _datas,
    hiddenimports=[
        "app", "agent", "local_worker",
        "pystray._win32", "PIL.Image", "PIL.ImageDraw",
        "playwright.sync_api",
        "uvicorn.logging", "uvicorn.loops.auto", "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets.auto", "uvicorn.lifespan.on",
    ] + _hidden,
    hookspath=[],
    runtime_hooks=["pyi_rth_playwright.py"],
    excludes={excludes},
    noarchive=False,
)
pyz = PYZ(a.pure)
# ONE-DIR: no runtime extraction (avoids the one-file decompression failure on
# large chrome.dll / cv2.pyd).
exe = EXE(
    pyz, a.scripts, [],
    exclude_binaries=True,
    name="ArtworkStudio",
    debug=False, bootloader_ignore_signals=False, strip=False,
    upx=False, console={console}, disable_windowed_traceback=False,
)
coll = COLLECT(
    exe, a.binaries, a.datas,
    strip=False, upx=False, name="ArtworkStudio",
)
'''


def main() -> None:
    root = Path(__file__).parent
    chrome_dir = chromium_folder()
    print(f"[build] bundling Chromium: {chrome_dir.name}  ({chrome_dir})")

    spec_path = root / "ArtworkStudio.spec"
    # Default to a windowed (no console) app; set STUDIO_BUILD_CONSOLE=1 to keep
    # a console for debugging.
    console = os.getenv("STUDIO_BUILD_CONSOLE") == "1"
    spec_path.write_text(_SPEC_TEMPLATE.format(
        chrome_dir=str(chrome_dir), chrome_name=chrome_dir.name,
        root=str(root), excludes=repr(EXCLUDES), console=str(console),
    ), encoding="utf-8")

    print("[build] running PyInstaller from generated spec…")
    subprocess.check_call(
        [sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean", str(spec_path)],
        cwd=str(root),
    )

    app_dir = root / "dist" / "ArtworkStudio"
    exe = app_dir / "ArtworkStudio.exe"
    if not exe.exists():
        print("[build] FAILED — dist/ArtworkStudio/ArtworkStudio.exe not found.")
        sys.exit(1)

    folder_bytes = sum(f.stat().st_size for f in app_dir.rglob("*") if f.is_file())

    import shutil
    zip_base = root / "dist" / "ArtworkStudio"
    print("[build] zipping the app folder for distribution…")
    zip_path = Path(shutil.make_archive(str(zip_base), "zip", root_dir=str(root / "dist"), base_dir="ArtworkStudio"))
    zip_bytes = zip_path.stat().st_size

    print()
    print(f"[build] DONE (one-dir): {app_dir}")
    print(f"[build] unpacked folder: {folder_bytes:,} bytes  (~{folder_bytes/(1024*1024):.0f} MB)")
    print(f"[build] download ZIP:    {zip_path}")
    print(f"[build] zip size:        {zip_bytes:,} bytes  (~{zip_bytes/(1024*1024):.0f} MB)")
    print("[build] Ship ArtworkStudio.zip. The designer unzips it, drops a .env")
    print("[build] beside ArtworkStudio.exe, and double-clicks the exe.")


if __name__ == "__main__":
    main()
